apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: apps-operator-job-runner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: apps-operator-job-runner-role
subjects:
- kind: ServiceAccount
  name: apps-operator-job-runner-sa
