apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: apps-operator-job-runner-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
