# permissions for end users to view customapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customapplication-viewer-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - customapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - customapplications/status
  verbs:
  - get
