# permissions for end users to edit customapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: customapplication-editor-role
rules:
- apiGroups:
  - apps.example.com
  resources:
  - customapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example.com
  resources:
  - customapplications/status
  verbs:
  - get
