resources:
- role.yaml 
- role_binding.yaml
- job_handler/role.yaml
- job_handler/runner.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
- auth_proxy_service.yaml
- auth_proxy_role.yaml
- auth_proxy_role_binding.yaml
- auth_proxy_client_clusterrole.yaml

# patchesJson6902:
#   - path: rolebinding_patch.yaml
#     target:
#       group: rbac.authorization.k8s.io
#       kind: RoleBinding
#       name: apps-operator-job-runner-rolebinding
#       version: v1